[project]
name = "iris-classifier"
version = "0.0.1"
description = ""
readme = "README.md"
require-python = ">3.8"
[[project.authors]]
email = "amazone6490@naver.com"
name = "Chae-seong Kim"
